### ISSUE TITLE
org-sticky-header doesn't work after jumping between headings

### ISSUE THREAD

**Issue by yuchen-lea** [alphapapa/org-sticky-header#22] opened 2020-12-27 04:45 UTC
I don't know why, it works at first, but stop working if:

1. mouse scroll too fast
2. use C-c C-n/C-p to jump between headings

In this situation, org-sticky-header mode is on, juse the sticky header disappears.

Issue demo：
![org-sticky-header-issue-2](https://user-images.githubusercontent.com/7555085/103163994-79975600-4840-11eb-8d4c-6fe68b91f5d2.gif)
(sorry that my notes are all chinese)

```
SYSTEM  type       darwin
        config     x86_64-apple-darwin19.6.0
        shell      /bin/zsh
        uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Dec 16, 2020
        buildopts  --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-mac/emacs-27.1-mac-8.0/share/info/emacs --prefix=/usr/local/Cellar/emacs-mac/emacs-27.1-mac-8.0 --with-mac --enable-mac-app=/usr/local/Cellar/emacs-mac/emacs-27.1-mac-8.0 --with-gnutls --with-modules
        features   NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER GMP
        traits     (gui server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      HEAD -> develop 0c9256411 2020-12-15 04:14:40 -0500
Org mode version 9.5
```

**Comment by alphapapa** [comment] 2020-12-27 19:10
Thanks for the thorough report and demonstration.

Can you reproduce this with `emacs -q`?

**Comment by yuchen-lea** [comment] 2020-12-28 10:45
Oh, I forget to do this before open the issue.

It works perfectly with emacs -q. Now I need to find the package or config conflicts with org-sticky-header

**Comment by alphapapa** [comment] 2020-12-28 18:52
Thanks.  Since it doesn't appear to be a bug in this package, I'm going to close the issue, but please let me know if you find what's causing the problem.

**Closed as completed by alphapapa** 2020-12-28 18:52 UTC

**Comment by yuchen-lea** [comment] 2021-01-02 09:26
It's the org-table-sticky-header-mode that conflicts.

I should have thought of this, since both of them stick in the first row.

Now, I'm trying to use both at the same time:

1. when no table: show header in the first row
2. when table: maybe show table header in the first row

All in all, thanks for pointing out the right direction to debug!
